# To use:
#
#     pre-commit run -a
#
# Or:
#
#     pre-commit install  # (runs every time you commit in git)
#
# To update this file:
#
#     pre-commit autoupdate
#
# See https://pre-commit.com for more information

# Do not check/format anything from third parties
exclude: '^bower_components/leaflet'

# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
    - id: end-of-file-fixer
      exclude: '.json$'
    - id: mixed-line-ending
    - id: check-json
    - id: check-toml
    - id: check-yaml
    - id: check-added-large-files
      args: ['--maxkb=100']
    - id: requirements-txt-fixer
#  - id: fix-encoding-pragma
#    exclude: ^noxfile.py$

# documentation files: .rst
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
    - id: rst-backticks
    - id: rst-directive-colons
    - id: rst-inline-touching-normal

#- repo: https://github.com/asottile/pyupgrade
#  rev: v2.29.0
#  hooks:
#  - id: pyupgrade

# Changes tabs to spaces
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.5.5
  hooks:
  - id: remove-tabs
    exclude: 'Make.WarpX|Make.package|Makefile|GNUmake'

# Autoremoves unused Python imports
- repo: https://github.com/hadialqattan/pycln
  rev: v2.4.0
  hooks:
  - id: pycln
    name: pycln (python)

# Sorts Python imports according to PEP8
# https://www.python.org/dev/peps/pep-0008/#imports
- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
  - id: isort
    name: isort (python)
    args: ["--profile", "black", "--filter-files"]

# Python Formatting
- repo: https://github.com/psf/black
  rev: 24.4.2 # Keep in sync with blacken-docs
  hooks:
  - id: black
- repo: https://github.com/asottile/blacken-docs
  rev: 1.16.0
  hooks:
  - id: blacken-docs
    additional_dependencies:
    - black==24.4.2 # keep in sync with black hook
  # TODO: black-jupyter

# Jupyter Notebooks: clean up all cell outputs
- repo: https://github.com/roy-ht/pre-commit-jupyter
  rev: v1.2.1
  hooks:
  - id: jupyter-notebook-cleanup
    args:
      - --pin-patterns
      - "[pin];[donotremove]"
      # - --remove-kernel-metadata
